# Original .travis.yml from https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
language: go
go:
  - 1.11.x

env:
  - GO111MODULE=on

before_script:
  - go get github.com/golang/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/mattn/goveralls

script:
  - bash ./ci_script.sh
  - $GOPATH/bin/goveralls -service=travis-ci
